import os
import sqlite3
from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'website.db')

# ─────────────────────────────────────────
# LTI 1.1 Config
# ─────────────────────────────────────────
LTI1_CONSUMER_KEY  = os.environ.get('LTI_CONSUMER_KEY', 'autograder_key')
LTI1_SHARED_SECRET = os.environ.get('LTI_SHARED_SECRET', 'autograder_secret')

# ─────────────────────────────────────────
# LTI 1.3 Config (from .env)
# ─────────────────────────────────────────
LTI13_CLIENT_ID      = os.environ.get('LTI13_CLIENT_ID', '')
LTI13_ISSUER         = os.environ.get('LTI13_ISSUER', 'https://canvas.instructure.com')
LTI13_AUTH_LOGIN_URL = os.environ.get('LTI13_AUTH_LOGIN_URL', '')
LTI13_AUTH_TOKEN_URL = os.environ.get('LTI13_AUTH_TOKEN_URL', '')
LTI13_KEY_SET_URL    = os.environ.get('LTI13_KEY_SET_URL', '')
LTI13_DEPLOYMENT_ID  = os.environ.get('LTI13_DEPLOYMENT_ID', '')

# Keys loaded from .key files (generated by openssl)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

def _load_key(filename):
    path = os.path.join(BASE_DIR, filename)
    if os.path.exists(path):
        with open(path, 'r') as f:
            return f.read()
    return ''

LTI13_PRIVATE_KEY = _load_key('private.key')
LTI13_PUBLIC_KEY  = _load_key('public.key')

# ─────────────────────────────────────────
# PyLTI1p3 Tool Config
# ─────────────────────────────────────────
def get_lti13_tool_conf():
    from pylti1p3.tool_config import ToolConfDict

    settings = {
        LTI13_ISSUER: [{
            'default':         True,
            'client_id':       LTI13_CLIENT_ID,
            'auth_login_url':  LTI13_AUTH_LOGIN_URL,
            'auth_token_url':  LTI13_AUTH_TOKEN_URL,
            'key_set_url':     LTI13_KEY_SET_URL,
            'deployment_ids':  [LTI13_DEPLOYMENT_ID],
        }]
    }

    tool_conf = ToolConfDict(settings)

    # Set keys directly from file contents
    tool_conf.set_private_key(LTI13_ISSUER, LTI13_PRIVATE_KEY, client_id=LTI13_CLIENT_ID)
    tool_conf.set_public_key(LTI13_ISSUER, LTI13_PUBLIC_KEY, client_id=LTI13_CLIENT_ID)

    return tool_conf

# ─────────────────────────────────────────
# State management for LTI 1.3 OIDC flow
# ─────────────────────────────────────────
def get_db():
    conn = sqlite3.connect(DB_PATH, timeout=10)
    conn.row_factory = sqlite3.Row
    return conn

def save_state(state, nonce):
    conn = get_db()
    c = conn.cursor()
    c.execute('INSERT OR REPLACE INTO lti_state (state, nonce) VALUES (?, ?)', (state, nonce))
    conn.commit()
    conn.close()

def verify_and_consume_state(state):
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM lti_state WHERE state=?', (state,))
    row = c.fetchone()
    if row:
        c.execute('DELETE FROM lti_state WHERE state=?', (state,))
        conn.commit()
    conn.close()
    return row is not None

def cleanup_old_states():
    conn = get_db()
    c = conn.cursor()
    c.execute("DELETE FROM lti_state WHERE created_at < datetime('now', '-10 minutes')")
    conn.commit()
    conn.close()